### ISSUE TITLE
Importing existing code creates the project and codespace - but not a build pipeline

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1678] opened 2017-07-09 03:08 UTC
If a user imports existing code - the codespace is created, but not the build pipeline.

**Comment by joshuawilson** [comment] 2017-07-25 02:26
@ldimaggi are you still seeing this?
@jstrachan do you know what is causing this?

**Comment by ldimaggi** [comment] 2017-07-26 15:02
Yes - this issue is still present.

**Comment by jstrachan** [comment] 2017-07-26 15:07
got an example project thats been imported?

**Comment by rgarg1** [comment] 2017-08-03 07:14
The issue is still reproducible. I used my brand new OSIO account today to import an untouched Vertx repo: https://github.com/rgargosiotest1/aug3a

The Pipelines were never started.

**Comment by jstrachan** [comment] 2017-08-08 12:00
this is fixed now - just waiting to get to prod

**Comment by jstrachan** [comment] 2017-08-08 13:15
its in prod

**Comment by ldimaggi** [comment] 2017-08-08 14:31
Just tried this - using a repo that I forked from a test repo that Burr created - https://github.com/ldimaggi/vertx-eventbus

The import worked cleanly - the app was deployed to stage and run in the pipeline - the pipeline was correctly included in the OSIO UI.

**Closed** 2017-08-09 07:31 UTC
Labels: area/app-wizard, area/pipelines, kind/bug, severity/blocker
