### ISSUE TITLE
Import wizard result displays [Object Object] due to forge addon API change

### ISSUE THREAD

**Issue by corinnekrych** [fabric8-ui/fabric8-ui#1857] opened 2017-08-10 12:27 UTC
![screenshot 2017-08-10 11 06 37](https://user-images.githubusercontent.com/1395710/29170264-fb3ae5d2-7dd7-11e7-92cc-5b5febd844d0.png)

**Comment by ldimaggi** [comment] 2017-08-10 12:35
Duplicate of:  https://github.com/openshiftio/openshift.io/issues/483

**Closed** 2017-08-13 02:17 UTC
Labels: area/app-wizard
